-- MySQL Script generated by MySQL Workbench
-- Mon Jul  5 18:53:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wedostudio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wedostudio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wedostudio` DEFAULT CHARACTER SET utf8 ;
USE `wedostudio` ;

-- -----------------------------------------------------
-- Table `wedostudio`.`avatars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`avatars` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `keywords` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL,
  `level` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `discount` INT(11) NULL DEFAULT NULL,
  `initialCapacity` INT(11) NOT NULL,
  `minimalCapacity` INT(11) NOT NULL,
  `actualCapacity` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `specs` TEXT NULL DEFAULT NULL,
  `keywords` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `discount` INT(11) NULL DEFAULT NULL,
  `stock` INT(11) NOT NULL,
  `stockMin` INT(11) NOT NULL,
  `stockMax` INT(11) NOT NULL,
  `categoryId` INT(11) NOT NULL,
  `brandId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoryId` (`categoryId` ASC) VISIBLE,
  INDEX `brandId` (`brandId` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `wedostudio`.`categories` (`id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`brandId`)
    REFERENCES `wedostudio`.`brands` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `productId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `wedostudio`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`migrations` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedostudio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NULL DEFAULT NULL,
  `avatarId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `avatarId` (`avatarId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`avatarId`)
    REFERENCES `wedostudio`.`avatars` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`states` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `orderNumber` INT(11) NOT NULL,
  `total` DECIMAL(10,0) NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `userId` INT(11) NOT NULL,
  `stateId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  INDEX `stateId` (`stateId` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `wedostudio`.`users` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`stateId`)
    REFERENCES `wedostudio`.`states` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `keywords` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `discount` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`orderdetails` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  `subtotal` DECIMAL(10,0) NOT NULL,
  `orderId` INT(11) NOT NULL,
  `productId` INT(11) NOT NULL,
  `serviceId` INT(11) NOT NULL,
  `courseId` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `orderId` (`orderId` ASC) VISIBLE,
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `serviceId` (`serviceId` ASC) VISIBLE,
  INDEX `courseId` (`courseId` ASC) VISIBLE,
  CONSTRAINT `orderdetails_ibfk_1`
    FOREIGN KEY (`orderId`)
    REFERENCES `wedostudio`.`orders` (`id`),
  CONSTRAINT `orderdetails_ibfk_2`
    FOREIGN KEY (`productId`)
    REFERENCES `wedostudio`.`products` (`id`),
  CONSTRAINT `orderdetails_ibfk_3`
    FOREIGN KEY (`serviceId`)
    REFERENCES `wedostudio`.`services` (`id`),
  CONSTRAINT `orderdetails_ibfk_4`
    FOREIGN KEY (`courseId`)
    REFERENCES `wedostudio`.`courses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wedostudio`.`seeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedostudio`.`seeds` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
